openapi: 3.1.0
info:
  title: Card Collecting App API
  version: 1.0.0
  description: API for managing users, collections, series, sets, cards, and decks.
servers:
  - url: http://localhost:3000/api
    description: Local development server
  - url: https://card-collect-api.onrender.com/api
    description: Production server
security:
  - bearerAuth: []
tags:
  - name: Users
    description: Endpoints for user management and authentication
  - name: Series
    description: Endpoints for trading card series (admin only for some operations)
  - name: Sets
    description: Endpoints for card sets (admin only for some operations)
  - name: Cards
    description: Endpoints for individual cards (admin only for some operations)
  - name: Decks
    description: Endpoints for user decks
paths:
  /auth/register:
    post:
      summary: Register a new user
      tags:
        - Users
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/NotAuthorized'
  /auth/login:
    post:
      summary: User login
      tags:
        - Users
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Auth token returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
        '401':
          $ref: '#/components/responses/NotAuthorized'
  /users/me:
    get:
      summary: Get current user info
      tags:
        - Users
      responses:
        '200':
          description: Current user data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/NotAuthorized'
    put:
      summary: Update current user info
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
      responses:
        '200':
          description: Updated user info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/NotAuthorized'
  /users/me/collection:
    get:
      summary: Get current user's collection
      tags:
        - Users
      responses:
        '200':
          description: User collection
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Card'
        '401':
          $ref: '#/components/responses/NotAuthorized'
    post:
      summary: Add a card to current user's collection
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cardId:
                  type: integer
                condition:
                  type: string
      responses:
        '201':
          description: Card added to collection
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Card'
        '401':
          $ref: '#/components/responses/NotAuthorized'
  /series:
    get:
      summary: List all series
      tags:
        - Series
      responses:
        '200':
          description: Series list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Series'
    post:
      summary: Create a new series (Admin only)
      tags:
        - Series
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                publisher:
                  type: string
      responses:
        '201':
          description: Series created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Series'
        '403':
          $ref: '#/components/responses/NotAuthorized'
  /series/{id}:
    get:
      summary: Get a specific series
      tags:
        - Series
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Series details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Series'
        '401':
          $ref: '#/components/responses/NotAuthorized'
    put:
      summary: Update a series (Admin only)
      tags:
        - Series
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                publisher:
                  type: string
      responses:
        '200':
          description: Series updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Series'
        '403':
          $ref: '#/components/responses/NotAuthorized'
    delete:
      summary: Delete a series (Admin only)
      tags:
        - Series
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '403':
          $ref: '#/components/responses/NotAuthorized'
  /sets:
    get:
      summary: List all sets
      tags:
        - Sets
      responses:
        '200':
          description: List of sets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Set'
    post:
      summary: Create a new set (Admin only)
      tags:
        - Sets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                series_id:
                  type: integer
                set_cards:
                  type: integer
      responses:
        '201':
          description: Set created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Set'
        '403':
          $ref: '#/components/responses/NotAuthorized'
  /sets/{id}:
    get:
      summary: Get a specific set
      tags:
        - Sets
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Set details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Set'
        '401':
          $ref: '#/components/responses/NotAuthorized'
    put:
      summary: Update a set (Admin only)
      tags:
        - Sets
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Set updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Set'
        '403':
          $ref: '#/components/responses/NotAuthorized'
    delete:
      summary: Delete a set (Admin only)
      tags:
        - Sets
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '403':
          $ref: '#/components/responses/NotAuthorized'
  /cards:
    get:
      summary: List all cards
      tags:
        - Cards
      responses:
        '200':
          description: List of cards
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Card'
    post:
      summary: Create a new card (Admin only)
      tags:
        - Cards
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                set_id:
                  type: integer
                variation:
                  type: string
                number:
                  type: string
      responses:
        '201':
          description: Card created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Card'
        '403':
          $ref: '#/components/responses/NotAuthorized'
  /cards/{id}:
    get:
      summary: Get a specific card
      tags:
        - Cards
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Card details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Card'
        '401':
          $ref: '#/components/responses/NotAuthorized'
    put:
      summary: Update a card (Admin only)
      tags:
        - Cards
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                variation:
                  type: string
      responses:
        '200':
          description: Card updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Card'
        '403':
          $ref: '#/components/responses/NotAuthorized'
    delete:
      summary: Delete a card (Admin only)
      tags:
        - Cards
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '403':
          $ref: '#/components/responses/NotAuthorized'
  /users/me/decks:
    get:
      summary: Get current user's decks
      tags:
        - Decks
      responses:
        '200':
          description: List of decks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Deck'
        '401':
          $ref: '#/components/responses/NotAuthorized'
    post:
      summary: Create a new deck
      tags:
        - Decks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                format:
                  type: string
                description:
                  type: string
      responses:
        '201':
          description: Deck created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deck'
        '401':
          $ref: '#/components/responses/NotAuthorized'
  /users/me/decks/{id}:
    get:
      summary: Get a specific deck
      tags:
        - Decks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Deck details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deck'
        '401':
          $ref: '#/components/responses/NotAuthorized'
    put:
      summary: Update a deck
      tags:
        - Decks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                format:
                  type: string
                description:
                  type: string
      responses:
        '200':
          description: Deck updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deck'
        '401':
          $ref: '#/components/responses/NotAuthorized'
    delete:
      summary: Delete a deck
      tags:
        - Decks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '401':
          $ref: '#/components/responses/NotAuthorized'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        username:
          type: string
          example: collector1
        email:
          type: string
          example: user@email.com
    AuthToken:
      type: object
      properties:
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5...
    Card:
      type: object
      properties:
        id:
          type: integer
          example: 10
        name:
          type: string
          example: Charizard
        set_id:
          type: integer
          example: 1
        variation:
          type: string
          example: Holographic
        number:
          type: string
          example: 4/102
        image_url:
          type: string
          example: https://example.com/charizard.png
        condition:
          type: string
          example: Near Mint
    Series:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Pokémon TCG
        publisher:
          type: string
          example: Nintendo
    Set:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Base Set
        series_id:
          type: integer
          example: 1
        set_cards:
          type: integer
          example: 102
    Deck:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: My Fire Deck
        format:
          type: string
          example: Standard
        description:
          type: string
          example: My first deck
        cards:
          type: array
          items:
            type: object
            properties:
              cardId:
                type: integer
                example: 10
              name:
                type: string
                example: Charizard
              quantity:
                type: integer
                example: 1
  responses:
    NotAuthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Unauthorized
    NoContent:
      description: No Content
